environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py36
    - TOXENV: ipython
    - TOXENV: numpy

matrix:
  fast_finish: true

build: false

install: C:\Python36\python -m pip install -U tox

test_script: C:\Python36\scripts\tox
